import os
import json
import requests
from config import WEATHER_API_KEY, LOCATION, SAMPLE_WEATHER_PATH


# the sample dataset is compatible with the structure generated by the
# openweathermap fetcher; it contains a couple of entries that mirror the
# forecast listed in your message so we can verify generation when no API key
# is provided.
_SAMPLE_DATA = [
    {"dt_txt": "2026-02-25 09:00:00", "main": {"temp": 55}, "weather": [{"description": "clear sky"}]},
    {"dt_txt": "2026-02-25 12:00:00", "main": {"temp": 56}, "weather": [{"description": "few clouds"}]},
    # ... additional sample entries omitted for brevity
]


def fetch_weather():
    """Return a list of dicts with keys ``time`` ``temp`` and ``description``.

    If there is no API key configured or the request fails, fall back to the
    sample data stored alongside the package.
    """

    if not WEATHER_API_KEY:
        return _load_local_sample()

    url = (
        "https://api.openweathermap.org/data/2.5/forecast"
        f"?q={LOCATION}&appid={WEATHER_API_KEY}&units=imperial"
    )
    try:
        r = requests.get(url, timeout=30)
        r.raise_for_status()
        data = r.json()
    except Exception:
        return _load_local_sample()

    result = []
    for entry in data.get("list", []):
        result.append({
            "time": entry["dt_txt"],
            "temp": entry["main"]["temp"],
            "description": entry["weather"][0]["description"],
        })
    return result


def _load_local_sample():
    if os.path.exists(SAMPLE_WEATHER_PATH):
        with open(SAMPLE_WEATHER_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        result = []
        for entry in data.get("list", []):
            result.append({
                "time": entry["dt_txt"],
                "temp": entry["main"]["temp"],
                "description": entry["weather"][0]["description"],
            })
        return result
    # fallback builtin samples
    return [
        {"time": item["dt_txt"], "temp": item["main"]["temp"], "description": item["weather"][0]["description"]}
        for item in _SAMPLE_DATA
    ]
